### ISSUE TITLE
Update to support re-importing legacy OBS to Catalog using RC 0.2

### ISSUE THREAD

**Issue by neutrinog** [neutrinog/dokuwiki-to-rc#1]
see https://github.com/unfoldingWord-dev/door43.org/issues/422

this would be a good opportunity to use the new python library you just created!

As a reminder the RC spec is at http://resource-container.readthedocs.io/en/latest/

**Comment by neutrinog** [comment]
@jeremymlane please note I already have a pending pull request at https://github.com/unfoldingWord-dev/dokuwiki-to-rc/pull/8. At that point I misunderstood the requirements so the code in that pull request is not completely accurate (see comments in PR).

**Comment by neutrinog** [comment]
@jeremymlane this looks really good. I have a few tweaks I'd like you to make.

* make sure all fields in the manifest are present even if the value is empty. Part of the RC requirements is that all fields be present. See https://git.door43.org/Door43/en-obs/raw/master/manifest.yaml for an example. For example the project block is missing the categories and sort.
* A number of fields in the manifest have default values. You can find these values in the link above. In particular:
  * contributor
  * creator
  * description
  * publisher
  * relation
  * rights
  * subject
  * sort (in the project block)

**Comment by neutrinog** [comment]
@jeremymlane to the last point (condensed vs expanded) we do want to write the chapters in condensed form. e.g. `content/01/01.md`. 

The concept of condensed vs expanded is outside the scope of the RC spec therefore it is perfectly valid to use the existing tooling (rc.write_chunk) to simple write a "normal" chunk that just happens to contain the entire chapter.

**Comment by jeremymlane** [comment]
@neutrinog Should the default values be worked into the python-resource-container library rather than here, or is that something that is specific to dokuwiki-to-rc?

**Comment by neutrinog** [comment]
the defaults are specific to dokuwiki-to-rc.

**Comment by jeremymlane** [comment]
@neutrinog Thanks. The default values are added now.

**Comment by neutrinog** [comment]
we will not add a config.yaml so I think this issue is done.
